Make cert install controlable in helm
cert-manager/istio-csr pull request #154
Opened 2022-05-09 14:39 UTC by marcingy

This add a helm value that allows for the default certificate not be installed. We have a use case in terms of how we are doing deployments and want to decouple releasing istio-csr from certificate creation for our mesh(s).

2022-05-09 21:03 UTC, lucarmcarlos approved these changes
Great commit, I was about to submit the same stuff

2022-05-09 21:03 UTC, lucarmcarlos commented
/assign @sgtcodfish

2022-05-10 08:28 UTC, SgtCoDFish commented
/ok-to-test

2022-05-10 12:09 UTC, lucarmcarlos commented
/marcingy

2022-05-18 13:29 UTC, JoshVanL requested changes
Thanks! Small nit from me :slightly_smiling_face:

2022-05-18 13:29 UTC, JoshVanL commented on deploy/charts/istio-csr/values.yaml
> +    issueDefaultCertificate: true
For some consistency :slightly_smiling_face: 

```suggestion
    istiodCertificateEnable: true
```

2022-05-18 13:29 UTC, JoshVanL commented on deploy/charts/istio-csr/templates/certificate.yaml
> +{{- if .Values.app.tls.issueDefaultCertificate }}
```suggestion
{{- if .Values.app.tls.istiodCertificateEnable }}
```

2022-05-18 13:29 UTC, JoshVanL commented on deploy/charts/istio-csr/README.md
> +| app.tls.issueDefaultCertificate | bool | `true` | Create the default certificate as part of install. |
```suggestion
| app.tls.istiodCertificateEnable | bool | `true` | Create the default certificate as part of install. |
```

2022-05-18 13:34 UTC, marcingy commented
/assign @SgtCoDFish

2022-06-10 11:35 UTC, JoshVanL commented
/lgtm

2022-06-10 11:52 UTC, SgtCoDFish approved these changes
/approve
/lgtm

(Approving since this has been LGTM'd, I haven't reviewed)

2022-06-10 12:07 UTC, merged