Increase bits to 4096 for more security
cert-manager/istio-csr pull request #167
Opened 2022-07-12 20:57 UTC by nitishkrishna

Signed-off-by: Nitish Krishna Kaveri <nitish.krishna@getcruise.com>

2022-07-18 13:32 UTC, JoshVanL requested changes
Thanks @nitishkrishna, couple comments from me!

2022-07-18 19:05 UTC, nitishkrishna commented
@JoshVanL Done! Thanks for the review!

2022-07-21 10:21 UTC, JoshVanL requested changes
Couple more things from me :slightly_smiling_face:

2022-07-21 10:21 UTC, JoshVanL commented on pkg/server/internal/extensions/extensions_test.go
> +	sk, err := pkiutil.GenerateRSAPrivateKey(4096)
It probably doesn't make sense for us to use `4096` key sizes in tests, since it is just going to slow things down for no real benefit.

2022-07-21 10:21 UTC, JoshVanL commented on cmd/app/options/options.go
> +	fs.StringVar(&o.TLS.ServingCertificateKeySize,
Can we also expose this option in the helm chart? `app.server.serving.certificateKeySize` probably makes the most sense.

2022-07-21 19:07 UTC, nitishkrishna commented
@JoshVanL updated and added to chart README as well

2022-07-22 09:14 UTC, JoshVanL commented
Thanks @nitishkrishna! :slightly_smiling_face: 

/lgtm
/approve
/ok-to-test

2022-07-22 09:19 UTC, JoshVanL commented
@nitishkrishna looks like you need to run `./hack/update-helm-docs.sh` and commit the changes.

2022-07-22 23:42 UTC, nitishkrishna commented
@JoshVanL looks good now, sorry about that

2022-07-25 07:52 UTC, JoshVanL commented
/lgtm

2022-07-25 07:52 UTC, merged