Allow the TrustDomain to be set.
cert-manager/istio-csr pull request #51
Opened 2021-05-07 22:20 UTC by janzantinge

This PR is meant to add support for custom trust domains to Istio CSR. It sets the domain in the SPIFFE library allowing for certificates with a the trust domain to be signed.

The tests were updated to specify a custom trust domain (`foo.bar`). LMK if there's a better way to test a change like this.

The Helm chart was updated as well, a new `value` was added: `trustDomain`.

2021-05-11 14:21 UTC, JoshVanL requested changes
Thanks @janzantinge! Just a couple comments from me.

/unassign
/assign @janzantinge 
/approve
/ok-to-test

2021-05-11 14:21 UTC, JoshVanL commented on cmd/app/options/options.go
> +	TrustDomain string
I think this is better suited to live under `TLSOptions.TrustDomain`.

2021-05-11 14:21 UTC, JoshVanL commented on cmd/app/options/options.go
> +		"The cluster's trust domain.")
```suggestion
		"The istio cluster's trust domain.")
```

2021-05-11 14:21 UTC, JoshVanL commented on deploy/charts/istio-csr/templates/deployment.yaml
> +          - "--trust-domain={{.Values.trustDomain}}"
```suggestion
          - "--trust-domain={{.Values.agent.trustDomain}}"
```

2021-05-12 19:00 UTC, janzantinge commented on hack/istio-config-1.7.6.yaml
> +      trustDomain: foo.bar
This took me a bit of time to figure out, updating all of these fields is required before Istio v1.8.0.

2021-05-12 19:38 UTC, JoshVanL commented
Thanks @janzantinge! This is a much needed addition.

/lgtm

2021-05-12 19:38 UTC, merged