Make all istio-csr internal services into runnables.
cert-manager/istio-csr pull request #71
Opened 2021-06-22 10:34 UTC by JoshVanL

This PR is branched from #69, which should be merged first.

This PR makes all internal services into controller-runtime runnables. This makes the code structure a lot cleaner, and means we have a single manager managing the long running packages.

Moves the readiness checks into controller-runtime.

Changes some of the chart values to reflect the new options structure.

/assign @jakexks

2021-06-22 10:55 UTC, JoshVanL commented
Failed due to old version of Go. Updated to v1.6

/test all

2021-06-22 11:26 UTC, JoshVanL commented
/retest

2021-06-29 15:36 UTC, irbekrm requested changes
Looks good to me- the refactor makes sense.

I've read through the code and tried to deploy with a few options including with multiple replicas- I saw that although only one replica runs the rootCA configmap controller all of them serve the gRPC API which was something I wasn't sure about.

I've added a couple of minor nits, but happy to lgtm.

2021-06-29 15:58 UTC, JoshVanL commented on pkg/tls/tls.go
> +	notAfter, err := p.fetchCertificate(ctx)
Yes, that's right. I think this is fine, all errors which come from this function failing are likely configuration issues.

2021-06-29 16:04 UTC, JoshVanL commented on pkg/tls/tls.go
> +			timer.Stop()
Yes, that sounds like a good addition.

2021-06-29 16:08 UTC, JoshVanL commented on cmd/app/app.go
> +				return fmt.Errorf("failed to add kubernetes scheme: %s", err)
Why?

2021-06-29 16:52 UTC, irbekrm commented
/test pull-istio-csr-k8s-v1-21-istio-v1-9

2021-06-29 16:53 UTC, irbekrm commented on cmd/app/app.go
> +				return fmt.Errorf("failed to add kubernetes scheme: %s", err)
so that it's a string for '%s' 🤷🏼‍♀️

2021-06-29 17:15 UTC, irbekrm commented
Looks good to me, thanks for making the changes!

/lgtm

2021-06-29 17:15 UTC, merged