Controller configmap refactor
cert-manager/istio-csr pull request #97
Opened 2021-09-17 11:48 UTC by JoshVanL

This PR refactors the controller to reduce the memory usage by only caching ConfigMap metadata, and not attempt to update/create ConfigMaps in terminating Namespaces.

Adds a Subscription channel so that the controller will reconcile on ConfigMaps in all Namespaces when the root CA changes.

/assign @irbekrm 

```release-note
NONE
```

2021-09-17 19:16 UTC, JoshVanL commented
/retest

2021-09-20 09:09 UTC, irbekrm requested changes
This looks great to me- the usage of a Watch with `Source` is nice 👍🏼 

I've added a couple nits and suggestions, else happy to approve.

2021-09-20 09:09 UTC, irbekrm commented on pkg/tls/tls.go
> +		if !bytes.Equal(p.rootCA, bundle.CA) {
Question: do we not want to send these event _after_ lines 315-322 where we could potentially error out of this func if the root CA was not decodeable?

2021-09-20 09:52 UTC, JoshVanL commented on pkg/controller/configmap.go
> +		Watches(&source.Kind{Type: new(corev1.Namespace)}, handler.EnqueueRequestsFromMapFunc(
It's fairly strongly worded by the controller-runtime docs to _not_ do something like this

https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete

2021-09-20 10:04 UTC, irbekrm commented on pkg/controller/configmap.go
> +		Watches(&source.Kind{Type: new(corev1.Namespace)}, handler.EnqueueRequestsFromMapFunc(
Cool, didn't know this 👍🏼

2021-09-20 11:21 UTC, irbekrm approved these changes
/lgtm

2021-09-20 11:31 UTC, irbekrm commented
/lgtm

2021-09-20 11:42 UTC, merged